### ISSUE TITLE
Update WebLaF to 1.2.9

### ISSUE THREAD

**Issue by StarHack** [GraxCode/Cafebabe#5]
**Cafebase version:** 0.1.2
**Java version:** Adopt OpenJDK version "11" 2018-09-25
**OS:** macOS 10.14.6

The following exception occurred when launching Cafebase on macOS:

<img width="1023" alt="cafebase-exception" src="https://user-images.githubusercontent.com/5388534/64235187-20433f00-cef8-11e9-88a5-b6bbae4c25d2.png">

Once the application was shown it came with an opaque border and I could not resize the window:

<img width="626" alt="cafebase-opaque" src="https://user-images.githubusercontent.com/5388534/64235284-479a0c00-cef8-11e9-82dc-5b5168ac4c2d.png">

**Comment by GraxCode** [comment]
Which Java version are you using? Try with java 8, i think WebLaF doesn't support newer java versions. I maybe will have to switch to WebLaF 1.2.9, but it is much different to 1.2.8 so I'd have to recode the whole GUI.

**Comment by GraxCode** [comment]
I have added a setting to disable decorated frames / dialogues for now.

**Comment by StarHack** [comment]
@GraxCode The decorated frame / theme works fine for Java 8 indeed. Many thanks for implementing the new setting! Und Grüsse aus Zürich. ;-)
